export default function Head() {
  return (
    <>
      <title>Portfolio - RRM</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://csstools.github.io/normalize.css/11.0.0/normalize.css" crossOrigin={'true'} />
    </>
  )
}
